-- MySQL

SELECT NAME
FROM ANIMAL_INS
ORDER BY DATETIME ASC
LIMIT 1 -- LIMIT 활용 

-- Oracle

SELECT NAME
FROM (SELECT NAME, DATETIME FROM ANIMAL_INS ORDER BY DATETIME ASC)
WHERE rownum <= 1 -- rownum 활용 