-- GROUP BY 이용하기
-- Oracle
SELECT COUNT(*)
FROM (SELECT NAME
     FROM ANIMAL_INS
     WHERE NAME IS NOT NULL
     GROUP BY NAME)
     
-- MySQL : Alias 필요 
SELECT COUNT(*)
FROM (SELECT NAME
     FROM ANIMAL_INS
     WHERE NAME IS NOT NULL
     GROUP BY NAME) AS A

-- DISTINCT 이용하기 
SELECT COUNT(DISTINCT NAME)
FROM ANIMAL_INS
WHERE NAME IS NOT NULL